version: "3"

services:
  greenbot:
    container_name: greenbot
    image: ghcr.io/greenm4x/greenbot:latest
    # ports:
    #   - 9595:8080
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - LAVALINK_HOST=${LAVALINK_HOST}
      - LAVALINK_PW=${LAVALINK_PW}
    restart: unless-stopped
    volumes:
      - ../../databases/db.json:/GreenBot/db.json:rw
      - ../../databases/cardInfo.json:/GreenBot/db/cardInfo.json:rw
      - ../../databases/images:/GreenBot/db/images:rw
      - ../../databases/booster_packs:/GreenBot/db/booster_packs:rw
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
